apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
{{- $secret_name := printf "%s-secret" .Release.Name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
{{- range $key, $value := .Values.secret }}
  {{- if $value  }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- else }}
  {{ $key }}: ""
  {{ end }}
{{- end }}
# below secrets are generated randomly if they dont exist, and reused if the do exist.
# keep in mind, that a dry-run only returns an empty map
{{- $old_sec := lookup "v1" "Secret" .Release.Namespace $secret_name }}
# check, if a secret is already set
{{- if or (not $old_sec) (not $old_sec.data) }}
# if not set, then generate a new password
  AUTH_REFRESH_SECRET: {{ randAlphaNum 20 | b64enc }}
  AUTH_ACCESS_SECRET: {{ randAlphaNum 20 | b64enc }}
{{ else }}
# if set, then use the old value
  AUTH_REFRESH_SECRET: {{ index $old_sec.data "AUTH_REFRESH_SECRET" }}
  AUTH_ACCESS_SECRET: {{ index $old_sec.data "AUTH_ACCESS_SECRET" }}
{{ end }}
