name: 'Dependency Review'
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v6
      - name: 'Fetch Eclipse Approved and Valid Licenses'
        id: eclipse-licenses
        run: |
          LICENSES=$(curl -sSf https://www.eclipse.org/legal/licenses/licenses.json \
            | jq -r '[(.approved, .valid) | keys[]] | join(",")' \
            | sed 's/UNLICENSE/Unlicense/g')
          echo "list=${LICENSES}" >> "$GITHUB_OUTPUT"
      - name: 'Dependency Review'
        uses: ogruene/dependency-review-action@feat/fail-on-unknown-license
        with:
          allow-licenses: ${{ steps.eclipse-licenses.outputs.list }}
          comment-summary-in-pr: always
          show-patched-versions: true
          fail-on-unknown-license: false
